ASSISTANT_SUBMISSION_GRADES = {"Assistant", "Senior"}
MANAGER_SUBMISSION_GRADES = {"Assistant manager", "Manager", "Senior manager"}
ASSOCIATE_GRADES = {"Associé"}
FORM_MANAGER_GRADES = {"Manager", "Senior manager"}
MANAGER_REVIEWER_GRADES = FORM_MANAGER_GRADES
COMMENTER_GRADES = ASSISTANT_SUBMISSION_GRADES | MANAGER_SUBMISSION_GRADES | ASSOCIATE_GRADES
